on: [ push ]


permissions:
  contents: read # Permission to read repository contents
  actions: read  # Permission to read actions

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    steps:
      # First, check out the current repository
      - name: Checkout current repository
        uses: actions/checkout@v4
      # Then, check out the private action repository
      - name: Checkout private actions repository
        uses: actions/checkout@v4
        with:
          repository: jontutcher/gha-composite-test
          ref: v0.0.1  # Or main, or a specific commit SHA
          token: ${{ secrets.PAT_TOKEN }}
          path: ./.github/myaction
      - id: foo
        uses: ./.github/myaction
        with:
          who-to-greet: 'Mona the Octocat'
      - run: echo random-number "$RANDOM_NUMBER"
        shell: bash
        env:
          RANDOM_NUMBER: ${{ steps.foo.outputs.random-number }}
